# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ebfadca3f9c7e65a3f642ef325f24da6"
name = "CSV変換"
application_url = "https://peony-csv-export.onrender.com"
embedded = false

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = ["https://peony-csv-export.onrender.com/auth/callback"]
